### PR TITLE
Bank marketing

### PR DESCRIPTION
**Pull request by dfalbel**
Use a local branch so tests can use thje kaggle auth token
See #10 for the original PR.

### CODE REVIEW

**Comment by dfalbel** [comment]
Hey @dkgaraujo ! Thanks very much for your PR and sorry for taking so long to respond - I was on vacations the last 2 weeks.
I merged your PR to a local branch so tests can use the kaggle auth token.

The `initialize` method of the dataset is perfect IMO! However the dataset is not yet usable because we need to implement the `.getitem` and the `.lenght` methods so we can use it with dataloaders. Do you want to implement them?

Thanks very much!!

**Comment by dkgaraujo** [comment]
Happy go implement them, @dfalbel. Will revert back. Other then the two methods you mentioned, is there any action needed to address the R-CMD-checks?

**Review by dkgaraujo — COMMENTED** [review]
I have recoded the initialize() method to return the dataset all in numeric form (including the categorical variables), and also created the .getitem() and .length() methods. Will be submitting soon.

**Comment by dfalbel** [comment]
Thanks @dkgaraujo ! Looks great!
When running the tests I still get a warning though:

```
Warning (test-bank-marketing.R:3:3): bank marketting works
33425 parsing failures.
 row         col               expected actual                                                                                                                                   file
7764 nr.employed no trailing characters     .1 '/var/folders/x0/fqbv9_ys1lq55xqjqbqllzqm0000gn/T/RtmpWcbaGo/filefbc732857ce8/bank-marketing/bank-additional/bank-additional-full.csv'
7765 nr.employed no trailing characters     .1 '/var/folders/x0/fqbv9_ys1lq55xqjqbqllzqm0000gn/T/RtmpWcbaGo/filefbc732857ce8/bank-marketing/bank-additional/bank-additional-full.csv'
7766 nr.employed no trailing characters     .1 '/var/folders/x0/fqbv9_ys1lq55xqjqbqllzqm0000gn/T/RtmpWcbaGo/filefbc732857ce8/bank-marketing/bank-additional/bank-additional-full.csv'
7767 nr.employed no trailing characters     .1 '/var/folders/x0/fqbv9_ys1lq55xqjqbqllzqm0000gn/T/RtmpWcbaGo/filefbc732857ce8/bank-marketing/bank-additional/bank-additional-full.csv'
7768 nr.employed no trailing characters     .1 '/var/folders/x0/fqbv9_ys1lq55xqjqbqllzqm0000gn/T/RtmpWcbaGo/filefbc732857ce8/bank-marketing/bank-additional/bank-additional-full.csv'
.... ........... ...................... ...... ......................................................................................................................................
See problems(...) for more details.
```

We should fix it or at least silence it if this is really expected.

**Review by dkgaraujo — APPROVED** [review]

**Comment by dkgaraujo** [comment]
@dfalbel Hope the actions above addressed the points you made. Please let me know if there is any further action needed from my side.

**Comment by dfalbel** [comment]
Hi @dkgaraujo ,

It would be great if we could fix this warning: https://github.com/mlverse/torchdatasets/pull/11#issuecomment-807520159 before merging. We should make sure this is not an issue when reading the dataset, and if everything is fine we can silence it using `suppressWarnings` or something similar.

**Comment by dkgaraujo** [comment]
@dfalbel One thing that occurred to me is that the pull request should also change README.md to incorporate the new dataset in that list. How would you advise that I proceed - reopen this one, or you change yourself, etc? Feel free to let me know. Thanks & cheers.

**Comment by dkgaraujo** [comment]
Hi @dfalbel - I just wanted to check if there is anything from my side that is needed before this could be merged, and if all CI tests passed well. Please let me know when convenient for you, and I'll be happy to follow up.

**Pull request merged**
